version: '3.8'

services:
  server:
    depends_on:
      - db
      - db-test
      - zoo1
      - kafka1
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - KAFKA_BROKERS=kafka1:19092
    ports:
      - 8080:8080
